name: Hub Terraform
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ENV: Barings_Hub
  VAR_FILE: terraform.tfvars
  ARM_CLIENT_ID: "6242b26e-cb07-4578-92b4-75fab33366fd"
  ARM_CLIENT_SECRET: "dc404762-c414-47c4-a548-f8f6b8d7bb99"
  ARM_TENANT_ID: "6a8ff3cc-d3cc-4944-9654-edad9087dfdc"
  ARM_SUBSCRIPTION_ID: "0992e5b4-51f7-4ac6-ab8a-d96bfc3b69a0"
  TF_TFSTATE_CONTAINER_NAME: "baringstfhubstate"
  TF_TFSTATE_RESOURCE_GROUP_NAME: "BaringsTF"
  TF_TFSTATE_STORAGE_ACCOUNT_NAME: "baringstfhubsa"
jobs:
- job: Terraform
  steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 0.12.25

  - bash: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'
    displayName: 'Install AZ CLI'

  - task: Bash@3
    displayName: 'AZ Login'
    inputs:
      targetType: filePath
      filePath: ./backend/azlogin.sh

  - task: Bash@3
    displayName: 'Setup Backend'
    inputs:
      targetType: filePath
      filePath: ./backend/setup_backend.sh

  - task: Bash@3
    inputs:
      targetType: filePath
      filePath: ./backend/tf_scaffolding.sh
    displayName: 'Terraform Scaffolding'
  - bash: 'terraform init'
    displayName: 'Terraform Init'
  - bash: 'terraform validate'
    displayName: 'Terraform Validate'

  - bash: 'terraform plan -out=${ENV}.tfplan'
    displayName: 'Terraform Plan'

  - bash: 'terraform apply -auto-approve -var-file=${VAR_FILE} ${ENV}.tfplan'
    displayName: 'Terraform Apply'